// Generated by gencpp from file table_simulator/Gaze.msg
// DO NOT EDIT!


#ifndef TABLE_SIMULATOR_MESSAGE_GAZE_H
#define TABLE_SIMULATOR_MESSAGE_GAZE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace table_simulator
{
template <class ContainerAllocator>
struct Gaze_
{
  typedef Gaze_<ContainerAllocator> Type;

  Gaze_()
    : offset(0.0)
    , distance(0.0)
    , angle(0.0)  {
    }
  Gaze_(const ContainerAllocator& _alloc)
    : offset(0.0)
    , distance(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef float _offset_type;
  _offset_type offset;

   typedef float _distance_type;
  _distance_type distance;

   typedef float _angle_type;
  _angle_type angle;




  typedef boost::shared_ptr< ::table_simulator::Gaze_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::table_simulator::Gaze_<ContainerAllocator> const> ConstPtr;

}; // struct Gaze_

typedef ::table_simulator::Gaze_<std::allocator<void> > Gaze;

typedef boost::shared_ptr< ::table_simulator::Gaze > GazePtr;
typedef boost::shared_ptr< ::table_simulator::Gaze const> GazeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::table_simulator::Gaze_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::table_simulator::Gaze_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace table_simulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'table_simulator': ['/home/harrison/catkin_ws/src/table_simulator/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::table_simulator::Gaze_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::table_simulator::Gaze_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::table_simulator::Gaze_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::table_simulator::Gaze_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::table_simulator::Gaze_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::table_simulator::Gaze_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::table_simulator::Gaze_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c58cf575410a1c3851d426cf912c3a4";
  }

  static const char* value(const ::table_simulator::Gaze_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c58cf575410a1c3ULL;
  static const uint64_t static_value2 = 0x851d426cf912c3a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::table_simulator::Gaze_<ContainerAllocator> >
{
  static const char* value()
  {
    return "table_simulator/Gaze";
  }

  static const char* value(const ::table_simulator::Gaze_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::table_simulator::Gaze_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 offset\n\
float32 distance\n\
float32 angle\n\
\n\
";
  }

  static const char* value(const ::table_simulator::Gaze_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::table_simulator::Gaze_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.offset);
      stream.next(m.distance);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gaze_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::table_simulator::Gaze_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::table_simulator::Gaze_<ContainerAllocator>& v)
  {
    s << indent << "offset: ";
    Printer<float>::stream(s, indent + "  ", v.offset);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TABLE_SIMULATOR_MESSAGE_GAZE_H
